<?php

namespace John\AdminBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends EntityRepository {

    public function getArticlesByCategory($category_slug)
    {
        $qb = $this->createQueryBuilder('a')
                ->leftJoin('a.category', 'c')
                ->addSelect('c')
                ->where('a.category = :category_slug')
                ->setParameter('category_slug', $category_slug)
                ->OrderBy('a.createdAt', 'DESC');

        return $qb->getQuery()
                        ->getResult();
    }
    
    public function getArticlesBySubCategory($sub_category_slug)
    {
        $qb = $this->createQueryBuilder('a')
                ->leftJoin('a.subCategory', 'sc')
                ->addSelect('sc')
                ->where('a.subCategory = :sub_category_slug')
                ->setParameter('sub_category_slug', $sub_category_slug)
                ->OrderBy('a.createdAt', 'DESC');

        return $qb->getQuery()
                        ->getResult();
    }

}
