<?php

namespace John\AdminBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends EntityRepository
{
    public function getArticlesByCategory($category)
    {
        $qb = $this->createQueryBuilder('a')
                ->leftJoin('a.category', 'c')
                ->addSelect('c')
                ->where('a.category = :category')
                ->setParameter('category', $category)
                ->OrderBy('a.createdAt', 'DESC');

        return $qb->getQuery()
                        ->getResult();
    }

    public function findAllBySubCategoryASCAndTitleASC()
    {
        $qb = $this->createQueryBuilder('a')
                ->leftJoin('a.subCategory', 'sc')
                ->addSelect('sc')
                ->leftJoin('sc.category', 'c')
                ->addSelect('c')
                ->OrderBy('c.title', 'ASC')
                ->OrderBy('sc.title', 'ASC')
                ->addOrderBy('a.updatedAt', 'ASC');

        return $qb->getQuery()
                        ->getResult();
    }

    public function getArticlesBySubCategory($subcategory)
    {
        $qb = $this->createQueryBuilder('a')
                ->leftJoin('a.subCategory', 'sc')
                ->addSelect('sc')
                ->where('a.subCategory = :subcategory')
                ->setParameter('subcategory', $subcategory)
                ->OrderBy('a.updatedAt', 'ASC');

        return $qb->getQuery()
                        ->getResult();
    }

//    public function getArticlesBySubCategoryWithPosition($subcategory)
//    {
//        $qb = $this->createQueryBuilder('a')
//                ->leftJoin('a.subCategory', 'sc')
//                ->addSelect('sc')
//                ->where('a.subCategory = :subcategory')
//                ->setParameter('subcategory', $subcategory)
//                ->OrderBy('a.updatedAt', 'ASC');
//
//        return $qb->getQuery()
//                        ->getResult();
//    }

//    public function getArticleBySubcategorySlugAndCategorySlug($category, $subcategory, $slug)
//    {
//        $qb = $this->createQueryBuilder('a')
//                ->where('a.slug = :article_slug')
//                ->setParameter('article_slug', $slug)
//                ->leftJoin('a.subCategory', 'sc')
//                ->addSelect('sc')
//                ->andWhere('a.subCategory = :subcategory')
//                ->setParameter('subcategory', $subcategory)
//                ->leftJoin('sc.category', 'c')
//                ->addSelect('c')
//                ->andWhere('sc.category = :category')
//                ->setParameter('category', $category);
//
//        return $qb->getQuery()
//                        ->getOneOrNullResult();
//    }

}