<?php

namespace John\AdminBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TagRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TagRepository extends EntityRepository
{
    public function getAutoCompleteTags()
    {
        $qb = $this->createQueryBuilder('t')
                ->orderBy('t.name', 'ASC');

        $results = $qb->getQuery()
                ->getArrayResult();

        $bufferArrayImplode = array();
        $bufferArray = array();

        if (!empty($results)) {
            foreach ($results as $result)
            {
                $bufferArray[] = '"' . $result['name'] . '"';
            }

            $bufferArrayImplode = '[' . implode(',', $bufferArray) . ']';
        }
        else {
            $bufferArrayImplode = null;
        }
        return $bufferArrayImplode;
    }

}